### ISSUE TITLE
[BUG] [Stack Three Columns] Shows three columns when editing questions

### ISSUE THREAD

**Issue by aelliott1485** [CertainPerformance/Stack-Exchange-Userscripts#13]
**Which userscript**
Stack Three Columns

**Describe the bug**
When editing a question, the three columns are displayed, which isn't really helpful

**To Reproduce**
1. On any post - e.g. https://codereview.stackexchange.com/questions/232757/fibonacci-and-lucas-sequence-generator-using-boost-and-gmp
2. Click on 'edit' for the question
3. The first column shows any answer or the empty answer form, which isn't really helpful at all when editing a question.

**Expected behavior**
Either the first column should be hidden, or else have a much smaller width.

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.4 
 - Browser Chrome
 - Browser Version 83.0.4103.106 (Official Build) (64-bit)
 - Userscript Manager Tampermonkey

**Additional context**
Thanks for sharing this very useful script. Let me know if you would like assistance with this.

**Comment by CertainPerformance** [comment]
This is by design. I think it's sometimes useful to be able to see the content and activity on answers when editing the question - for example, when an answer is posted with a Stack Snippet and you want to edit OP's broken code into a runnable snippet which will make it more obvious what the problem is. Or, when OP makes a comment (or few) on an answer that is essential information that should really be in the question. Or, when you'd like to see new answers and comments as they come in while editing the question.

Another thing is that this userscript is designed for those with wide screens who want to make full use of their screen real estate, close to Full HD or higher - and if there were only 2 columns, they would both be *pretty wide*, and wide columns with long lines are somewhat more difficult to read than narrower ones. (That's one reason why newspapers' columns are often narrow, and why the default Stack Exchange interface for the main content still only takes up around 1/3 of the screen, even for wide screens. Same for Github issues, Google results, and many other sites)

You're free to fork it and make the necessary changes if you want. Easiest tweak would be, in `openLayout`, check to see if the post root is of an answer being edited. If so, set `localStorage.cpUserscriptThreeColumnsAdjustable` to `{ firstColWidth: 0, secondColWidth: 50 }`, else to `33.33` and `33.33`. Then call `updateStyle`.
