### ISSUE TITLE
[Stack Three Columns] won't trigger when editing any answer.

### ISSUE THREAD

**Issue by 1898182** [CertainPerformance/Stack-Exchange-Userscripts#4]
<h3>Working:</h3>

- Copying snippet to answer
- Commenting a new answer

<h3>Not working:</h3>

- Editing an already answered post from any questions

<h3>Trying to understand why it didn't work</h3>

- I tried editing the @include original regex expression to simply `https://www.stackoverflow.com/*` because the script wasn't "*activating*".
- Afterwards, I opened the console and found out this error : 
<hr />

![](https://i.imgur.com/Rhujkeb.png)
<hr />

**Comment by CertainPerformance** [comment]
Do you have inline editing privileges (requires 2000 reputation)? If you don't, then the userscript does not give them to you - rather, the default behavior of the site is preserved, which takes you to the `https://stackoverflow.com/posts/POSTID/edit` page when you try to edit a post, and the userscript does not run on the `/edit` page.

(Similarly, the userscript doesn't run on the `/questions/ask` page, no matter the reputation)

At least, that's what happens currently. Is that your situation?

**Comment by 1898182** [comment]
Why having **inline editing privilege** would change anything? I can edit under 2000 reputation, I just need to get approved. 

Are you planning to adapt a two columns script for the `/questions/ask`?  That would be nice too. 👍

**Comment by makyen** [comment]
@1898182 It changes things because it's often significantly more work to write scripts so they work on additional pages. Sometimes it's not much, but often the script has to be adapted to the different HTML/CSS/JS which is provided for the alternate page. At an absolute minimum, it's something additional that the author has to test. In the case of this script, to use it on the `/edit` page wold be significant additional work, because all the question information doesn't exist on that page. The script would need to fetch the question information from somewhere else and insert it into the page. While that's not all that difficult, it is additional work. [There are a few different ways it could be done; I'd probably get it from the `ajax-load-realtime` SE-internal endpoint, or fetch the entire question page.]

So, while it would be nice for it to work on the additional pages, it's quite a bit easier to just use inline editing. You can have inline editing on all sites by installing the script: [Always Edit Inline](https://greasyfork.org/en/scripts/8587-always-edit-inline/code). Admittedly, that doesn't help with the `/questions/ask` page, but I expect that page would be significantly more work, particularly given that there are multiple different UIs which that page can show (i.e. with and without the new ask question wizard).

**Comment by 1898182** [comment]
@makyen Thanks for the explanation. I didn't notice that editing an existing question was redirecting me to another page. 

_Well, now I gotta aim for the 2k reputation!_
